const assert=require('assert/strict');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {randomUUID}=require('crypto');
const express=require('express');
const jwt=require('jsonwebtoken');
const sharp=require('sharp');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'yuyuko-journeys-'));
process.env.DB_FILE=path.join(temp,'test.sqlite');
process.env.LOG_TO_FILE='false';process.env.LOG_TO_CONSOLE='false';
process.env.DEEPSEEK_API_KEY='';process.env.JOURNEY_LLM_API_KEY='';process.env.SILICONFLOW_API_KEY='';
process.env.AMAP_WEB_SERVICE_KEY='';process.env.AMAP_JOURNAL_STORAGE_ALLOWED='false';process.env.AMAP_EXPORT_ALLOWED='false';
require.cache[require.resolve('../redis')]={exports:{isReady:()=>false}};
const {db,init}=require('../db');
const sql=db._raw;
const store=require('../services/journeyStore');
const ai=require('../services/journeyAI');
const nativeFetch=global.fetch;
let server,stopWorker;
async function main(){
    init();init();
    const user=name=>{const id=randomUUID();sql.prepare('INSERT INTO User(id,username,password) VALUES(?,?,?)').run(id,name,'unused');return id;};
    const a=user('日记测试甲'),b=user('日记测试乙');
    const places=Array.from({length:7},(_,i)=>Number(sql.prepare('INSERT INTO Place(name,category,longitude,latitude,per_person_cost) VALUES(?,?,?,?,?)').run(`测试餐馆${i}`,'面食',120+i*0.0001,30,35).lastInsertRowid));
    const tokens=Object.fromEntries([a,b].map(id=>[id,jwt.sign({id},process.env.JWT_SECRET||'yuyuko_secret_key')]));
    const app=express();app.use(express.json({limit:'256kb'}));app.use('/api/journeys',require('../routes/journeys'));app.use('/api/community',require('../routes/community'));
    server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
    const base=`http://127.0.0.1:${server.address().port}`;
    const call=async(method,url,body,who=a,status=200)=>{
        const response=await nativeFetch(base+url,{method,headers:{'Content-Type':'application/json',...(who?{Authorization:`Bearer ${tokens[who]}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});
        const data=response.status===204?null:await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;
    };
    const stop={id:randomUUID(),name:'测试餐馆0',source:'local',place_id:places[0],lng:120,lat:30,confirmed:true,visit_status:'visited',note:'只属于我的描述',media_ids:[],expenses:[{id:randomUUID(),amount:23.5,note:'晚饭'}]};
    const document={title:'周末',start_date:'2026-09-15',end_date:'2026-09-15',summary:'私人总结',stops:[stop]};
    await call('GET','/api/journeys',undefined,null,401);
    let journey=await call('POST','/api/journeys',{document},a,201);
    await call('GET',`/api/journeys/${journey.id}`,undefined,b,404);
    await call('PUT',`/api/journeys/${journey.id}`,{document,base_revision:1},b,404);
    await call('PUT',`/api/journeys/${journey.id}`,{document,base_revision:0},a,409);
    journey=await call('PUT',`/api/journeys/${journey.id}`,{document:{...document,title:'修改'},base_revision:1});assert.equal(journey.revision,2);
    journey=await call('POST',`/api/journeys/${journey.id}/restore`,{revision:1,base_revision:2});assert.equal(journey.document.title,'周末');assert.equal(journey.revision,3);
    await call('POST','/api/journeys',{document:{...document,start_date:'2026-02-31'}},a,400);
    await call('POST','/api/journeys',{document:{...document,stops:[null]}},a,400);
    await call('POST','/api/journeys',{document:{...document,stops:[{...stop,lng:181}]}},a,400);
    await call('POST','/api/journeys',{document:{...document,stops:[{...stop,media_ids:[randomUUID()]}]}},a,404);
    await call('POST','/api/journeys',{document:{...document,stops:[{...stop,source:'amap'}]}},a,400);
    const unresolved=await call('POST','/api/journeys',{document:{...document,start_date:'2026-09-16',end_date:'2026-09-16',stops:[{...stop,lng:null,lat:null,confirmed:false,visit_status:'unknown'}]}},a,201);
    const mergeInput={first_id:journey.id,second_id:unresolved.id,revisions:[3,1]};
    await call('POST','/api/journeys/merge',mergeInput,a,409);
    const mergePreview=await call('POST','/api/journeys/merge/preview',mergeInput);
    const merged=await call('POST','/api/journeys/merge',{...mergeInput,preview_hash:mergePreview.preview_hash},a,201);
    assert.equal(merged.document.stops.flatMap(s=>s.expenses).length,1);
    assert.equal((await call('POST','/api/journeys/merge',{...mergeInput,preview_hash:mergePreview.preview_hash},a,201)).id,merged.id);
    assert.equal(merged.document.stops.length,2);assert.equal(merged.document.sources.length,2);
    assert.equal((await call('GET','/api/journeys')).length,3);
    await call('POST','/api/journeys/merge',{first_id:journey.id,second_id:unresolved.id,revisions:[2,1]},a,409);
    const share=await call('POST',`/api/journeys/${journey.id}/share`,{base_revision:3,stop_ids:[stop.id]});
    assert.equal(share.generated,false);assert.ok(!share.text.includes('私人'));assert.ok(!share.text.includes('23.5'));assert.ok(!JSON.stringify(share).includes('只属于我的'));
    await call('POST',`/api/journeys/${unresolved.id}/share`,{base_revision:1,stop_ids:[stop.id]},a,400);
    await call('POST',`/api/journeys/${journey.id}/share`,{base_revision:2,stop_ids:[stop.id]},a,409);
    await call('POST',`/api/journeys/${journey.id}/cover-map`,{base_revision:3,stop_ids:[stop.id]},a,503);
    // Real image decoding, private reads, and removal of EXIF metadata.
    const photo=await sharp({create:{width:40,height:30,channels:3,background:'#f08050'}}).jpeg().withMetadata().toBuffer();
    const form=new FormData();form.append('image',new Blob([photo],{type:'image/jpeg'}),'test.jpg');
    const uploaded=await nativeFetch(base+'/api/journeys/media',{method:'POST',headers:{Authorization:`Bearer ${tokens[a]}`},body:form});assert.equal(uploaded.status,201);
    const {id:mediaId}=await uploaded.json();
    await call('GET',`/api/journeys/media/${mediaId}`,undefined,b,404);
    const imageResponse=await nativeFetch(`${base}/api/journeys/media/${mediaId}`,{headers:{Authorization:`Bearer ${tokens[a]}`}});
    const meta=await sharp(Buffer.from(await imageResponse.arrayBuffer())).metadata();assert.equal(meta.format,'webp');assert.equal(meta.exif,undefined);
    const withMedia=await call('POST','/api/journeys',{document:{...document,stops:[{...stop,media_ids:[mediaId]}]}},a,201);
    await call('DELETE',`/api/journeys/media/${mediaId}`,undefined,a,409);
    const mediaDraftId=randomUUID();
    await call('PUT',`/api/journeys/drafts/${mediaDraftId}`,{document:withMedia.document,draft_revision:0,base_revision:0});
    await call('DELETE',`/api/journeys/${withMedia.id}`,{base_revision:1},a,204);
    await call('DELETE',`/api/journeys/media/${mediaId}`,undefined,a,409);
    await call('DELETE',`/api/journeys/drafts/${mediaDraftId}`,{draft_revision:1},a,204);
    await call('DELETE',`/api/journeys/media/${mediaId}`,undefined,a,204);
    const consent0=await call('GET','/api/community/consent');assert.equal(consent0.feedback,false);assert.equal(consent0.discovery,false);
    const event={id:randomUUID(),session_id:randomUUID(),kind:'click',surface:'map',place_id:places[0]};
    assert.equal((await call('POST','/api/community/feedback',{events:[event],consent_version:0})).accepted,0);
    let consent=await call('PUT','/api/community/consent',{version:0,feedback:true,research:true,discovery:true,tags:['面食']});
    const observation=await call('POST','/api/community/observations',{consent_version:consent.version,place_ids:[places[0],places[1]]},a,201);
    const obsInput={snapshot_id:randomUUID(),search_session_id:randomUUID(),render_revision:randomUUID(),consent_version:consent.version,place_ids:[places[0],places[1]]};
    const obs1=await call('POST','/api/community/observations',obsInput,a,201);
    assert.equal((await call('POST','/api/community/observations',obsInput,a,201)).id,obs1.id);
    await call('POST','/api/community/observations',{...obsInput,place_ids:[places[1],places[0]]},a,409);
    event.decision_id=observation.id;event.surface='search';event.rank=0;
    await call('POST','/api/community/feedback',{events:[{...event,id:randomUUID(),surface:'map'}],consent_version:consent.version},a,400);
    await call('POST','/api/community/feedback',{events:[{...event,id:randomUUID(),rank:1}],consent_version:consent.version},a,400);
    for(const kind of ['favorite','unfavorite','confirm_stop'])await call('POST','/api/community/feedback',{events:[{...event,id:randomUUID(),kind}],consent_version:consent.version},a,400);
    const {changeFavorite}=require('../services/userPreferenceService');
    assert.equal(changeFavorite(a,places[6],true),true);assert.equal(changeFavorite(a,places[6],true),false);
    assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM MapInteraction WHERE user_id=? AND kind='favorite'").get(a).n,1);
    assert.equal(changeFavorite(a,places[6],false),true);assert.equal(changeFavorite(a,places[6],false),false);
    assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM MapInteraction WHERE user_id=? AND kind='unfavorite'").get(a).n,1);
    assert.equal((await call('POST','/api/community/feedback',{events:[event],consent_version:consent.version})).accepted,1);
    assert.equal((await call('POST','/api/community/feedback',{events:[event],consent_version:consent.version})).accepted,0);
    const drawInput={draw_id:randomUUID(),center:{lng:120,lat:30},exclude_ids:[places[0]],consent_version:consent.version};
    const draw=await call('POST','/api/community/draw',drawInput),retry=await call('POST','/api/community/draw',drawInput);
    assert.deepEqual(draw,retry);assert.notEqual(draw.place.id,places[0]);
    const snapshot=JSON.parse(sql.prepare('SELECT snapshot FROM MapDecision WHERE id=?').get(draw.decision_id).snapshot);
    assert.equal(snapshot.eligible_count,6);assert.ok(Math.abs(snapshot.candidates.reduce((n,c)=>n+c.probability,0)-1)<1e-10);
    assert.equal(snapshot.selected_probability,snapshot.candidates.find(c=>c.place_id===draw.place.id).probability);
    await call('POST','/api/community/feedback',{consent_version:consent.version,events:[
        {...event,id:randomUUID(),kind:'exposure',surface:'random',place_id:draw.place.id,decision_id:draw.decision_id},
        {...event,id:randomUUID(),kind:'click',surface:'random',place_id:draw.place.id,decision_id:draw.decision_id}
    ]});
    const {buildDataset,evaluateLoggedRandom}=require('../services/feedbackDataset');
    assert.throws(()=>buildDataset(sql,{secret:'x'.repeat(32)}));
    const dataset=buildDataset(sql,{secret:'x'.repeat(32),localDataAllowed:true});
    assert.ok(dataset.length>=3);assert.ok(!JSON.stringify(dataset).includes(a));assert.ok(!JSON.stringify(dataset).includes('120.000'));
    const evaluation=evaluateLoggedRandom(dataset);assert.equal(evaluation.exposed_decisions,1);assert.equal(evaluation.observed_click_rate,1);assert.equal(evaluation.uniform_policy_snips,1);
    await call('POST','/api/community/draw',{...drawInput,exclude_ids:[]},a,409);
    for(const id of [a,b])sql.prepare('INSERT INTO Favorite(user_id,place_id) VALUES(?,?)').run(id,places[0]);
    const cb=await call('POST','/api/community/collections',{title:'公开面食'},b,201);
    await call('PUT',`/api/community/collections/${cb.id}`,{title:'公开面食',place_ids:[places[0]],is_public:true},a,404);
    await call('PUT',`/api/community/collections/${cb.id}`,{title:'公开面食',place_ids:[places[1]],is_public:true},b,400);
    await call('PUT',`/api/community/collections/${cb.id}`,{title:'公开面食',place_ids:[places[0]],is_public:true},b);
    assert.equal((await call('GET','/api/community/neighbors')).neighbors.length,0);
    let bc=await call('PUT','/api/community/consent',{version:0,discovery:true,tags:['面食']},b);
    assert.equal((await call('GET','/api/community/neighbors')).neighbors.length,0,'One shared tag and one place must not produce a neighbor');
    for(const id of [a,b])for(const place of places.slice(1,3))sql.prepare('INSERT INTO Favorite(user_id,place_id) VALUES(?,?)').run(id,place);
    const ca=await call('POST','/api/community/collections',{title:'甲公开收藏'},a,201);
    await call('PUT',`/api/community/collections/${ca.id}`,{title:'甲公开收藏',place_ids:places.slice(0,3),is_public:true});
    await call('PUT',`/api/community/collections/${cb.id}`,{title:'乙公开收藏',place_ids:places.slice(0,3),is_public:true},b);
    const neighbors=await call('GET','/api/community/neighbors');assert.ok(neighbors.neighbors[0].similarity<=0.300001);assert.equal(neighbors.neighbors[0].id,b);assert.ok(!JSON.stringify(neighbors).includes('vector'));
    assert.equal((await call('GET',`/api/community/users/${b}/collections`)).collections.length,1);
    await call('PUT','/api/community/consent',{...bc,discovery:false},b);
    assert.equal((await call('GET','/api/community/neighbors')).neighbors.length,0);
    await call('GET',`/api/community/users/${b}/collections`,undefined,a,404);
    await call('PUT','/api/community/consent',{...consent,feedback:false,research:false});
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM MapInteraction WHERE user_id=?').get(a).n,0);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM MapDecision WHERE user_id=?').get(a).n,0);
    assert.equal((await call('POST','/api/community/feedback',{events:[{...event,id:randomUUID()}],consent_version:consent.version})).accepted,0);
    // Stub the provider boundary only. The durable worker and HTTP job lifecycle run for real.
    const original=global.fetch;
    process.env.JOURNEY_LLM_API_KEY='test-key-not-real';process.env.JOURNEY_LLM_BASE_URL='https://journey.test';
    let modelCalls=0;
    global.fetch=async(url,options)=>{
        assert.equal(String(url),'https://journey.test/chat/completions');modelCalls++;
        return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({title:'模型草稿',stops:[{name:'测试餐馆0',evidence:'去了测试餐馆0',visit_status:'visited'}]})}}]}),{status:200,headers:{'Content-Type':'application/json'}});
    };
    const jobInput={request_id:randomUUID(),text:'去了测试餐馆0',start_date:'2026-09-15',media_ids:[]};
    const job=await call('POST','/api/journeys/jobs',jobInput,a,202);
    assert.equal((await call('POST','/api/journeys/jobs',jobInput,a,202)).id,job.id);
    await call('POST','/api/journeys/jobs',{...jobInput,text:'different'},a,409);
    await call('GET',`/api/journeys/jobs/${job.id}`,undefined,b,404);
    stopWorker=ai.startJourneyWorker();
    let ready;
    for(let i=0;i<30;i++){ready=await call('GET',`/api/journeys/jobs/${job.id}`);if(ready.status==='ready')break;await new Promise(r=>setTimeout(r,100));}
    assert.equal(ready.status,'ready');assert.equal(modelCalls,1);assert.equal(ready.output.document.stops[0].confirmed,false);assert.deepEqual(ready.output.document.stops[0].expenses,[]);
    stopWorker();stopWorker=null;global.fetch=original;
    await call('DELETE',`/api/journeys/jobs/${job.id}`,undefined,a,204);
    await call('POST','/api/journeys/jobs',jobInput,a,410);
    for(let i=1;i<10;i++){
        const quotaJob=await call('POST','/api/journeys/jobs',{...jobInput,request_id:randomUUID()},a,202);
        await call('DELETE',`/api/journeys/jobs/${quotaJob.id}`,undefined,a,204);
    }
    await call('POST','/api/journeys/jobs',{...jobInput,request_id:randomUUID()},a,429);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyJobRequest WHERE user_id=?').get(a).n,10);
    const sequences=ai.rankSequence([[{id:'a',lng:120,lat:30,score:3},{id:'b',lng:80,lat:30,score:3}],[{id:'c',lng:120.01,lat:30,score:3}]]);
    assert.equal(sequences[0].id,'a');assert.equal(sequences[1].id,'c');
    const ambiguous=await ai.reconstruct(a,{text:'吃了面',start_date:'2026-09-15',end_date:'2026-09-15',media_ids:[]},{chat:async()=>({stops:[{name:'面馆',visit_status:'unknown'}]}),searchCandidates:async()=>[{id:'x',name:'面馆',lng:120,lat:30,score:3},{id:'y',name:'面馆',lng:121,lat:31,score:3}]});
    assert.equal(ambiguous.document.stops[0].lng,null);assert.equal(ambiguous.questions.length,1);assert.equal(ambiguous.document.stops[0].candidates[0].suggested,true);
    process.env.AMAP_WEB_SERVICE_KEY='test-amap-key';process.env.AMAP_JOURNAL_STORAGE_ALLOWED='true';process.env.AMAP_EXPORT_ALLOWED='true';
    const mapPng=await sharp({create:{width:960,height:640,channels:3,background:'#d9ead8'}}).png().toBuffer();
    global.fetch=async(url,options)=>{
        const parsed=new URL(String(url));
        if(parsed.pathname==='/v3/place/text') {
            assert.equal(parsed.searchParams.get('city'),'杭州');assert.equal(parsed.searchParams.get('citylimit'),'true');
            return new Response(JSON.stringify({status:'1',pois:[{id:'demo-poi',name:'测试分店',address:'测试路',location:'120.01,30.01'}]}),{headers:{'Content-Type':'application/json'}});
        }
        if(parsed.pathname==='/v3/staticmap') {assert.ok(parsed.searchParams.get('markers').includes('120.000000,30.000000'));return new Response(mapPng,{headers:{'Content-Type':'image/png'}});}
        assert.equal(parsed.hostname,'journey.test');
        const payload=JSON.parse(options.body);
        assert.ok(payload.messages[1].content[1].image_url.url.startsWith('data:image/webp;base64,'));
        return new Response(JSON.stringify({choices:[{message:{content:'{"text":"图片识别结果"}'}}]}),{headers:{'Content-Type':'application/json'}});
    };
    const amapCandidates=await ai.searchCandidates('测试分店','杭州',null);assert.equal(amapCandidates[0].source,'amap');assert.equal(amapCandidates[0].lng,120.01);
    const mapResponse=await nativeFetch(`${base}/api/journeys/${journey.id}/cover-map`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tokens[a]}`},body:JSON.stringify({base_revision:3,stop_ids:[stop.id]})});
    assert.equal(mapResponse.status,200);assert.equal(mapResponse.headers.get('content-type'),'image/png');
    process.env.JOURNEY_LLM_VISION='false';await assert.rejects(()=>ai.chat('test',{},[Buffer.from('test')]));
    process.env.JOURNEY_LLM_VISION='true';assert.equal((await ai.chat('test',{},[Buffer.from('test')])).text,'图片识别结果');
    global.fetch=original;
    // Merge ordering, explicit conflict resolution and stale preview protection.
    const mergeService=require('../services/journeyMerge');
    const mk=(id,hours,amount=30)=>({id,revision:1,document:{...document,title:id,stops:hours.map((h,i)=>({...stop,id:randomUUID(),at:'2026-09-15T'+h+':00',expenses:i?[]:[{id:'same-expense',amount,currency:'CNY',note:'饭钱'}]}))}});
    const ma=mk('source_a',['09','18']),mb=mk('source_b',['12']);
    const planned=mergeService.planMerge(ma,mb);
    assert.deepEqual(planned.document.stops.map(s=>s.at.slice(11,16)),['09:00','12:00','18:00']);assert.equal(planned.total_minor,3000);
    const timeConflict=mergeService.planMerge(mk('source_c',['18','09']),mb);
    assert.ok(timeConflict.conflicts.some(c=>c.type==='time_order'));
    assert.equal(mergeService.planMerge(mk('source_c',['18','09']),mb,{order_policy:'time'}).conflicts.length,0);
    const changedAmount=mk('source_d',['12'],40),feeConflict=mergeService.planMerge(ma,changedAmount);
    assert.equal(feeConflict.conflicts[0].type,'expense');
    assert.equal(mergeService.planMerge(ma,changedAmount,{expense_resolutions:{'same-expense':'separate'}}).total_minor,7000);
    const winner=feeConflict.conflicts[0].options[1].ref;
    assert.equal(mergeService.planMerge(ma,changedAmount,{expense_resolutions:{'same-expense':winner}}).total_minor,4000);
    await call('POST','/api/journeys/merge',{...mergeInput,order_policy:'time',preview_hash:mergePreview.preview_hash},a,409);
    const correctionDoc={...journey.document,stops:[{...journey.document.stops[0],name:'修正地点',place_id:places[1],correction_reason:'wrong_branch'}]};
    const baseline=sql.prepare('SELECT COUNT(*) AS n FROM JourneyCorrection').get().n;
    await call('PUT',`/api/journeys/${journey.id}`,{document:correctionDoc,base_revision:2},a,409);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyCorrection').get().n,baseline);
    sql.exec("CREATE TRIGGER test_correction_failure BEFORE INSERT ON JourneyCorrection BEGIN SELECT RAISE(ABORT,'test rollback'); END");
    await call('PUT',`/api/journeys/${journey.id}`,{document:correctionDoc,base_revision:3},a,500);
    assert.equal((await call('GET',`/api/journeys/${journey.id}`)).revision,3);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyCorrection').get().n,baseline);
    sql.exec('DROP TRIGGER test_correction_failure');
    await call('PUT',`/api/journeys/${journey.id}`,{document:correctionDoc,base_revision:3});
    const corrections=await call('GET',`/api/journeys/${journey.id}/corrections`);
    assert.equal(corrections.find(c=>c.field==='place').reason,'wrong_branch');
    assert.equal(corrections.find(c=>c.field==='place').before_value.place_id,places[0]);
    await call('GET',`/api/journeys/${journey.id}/corrections`,undefined,b,404);
    await call('POST','/api/journeys/merge',{...mergeInput,preview_hash:mergePreview.preview_hash},a,409);
    // Private draft writes accept unfinished forms, but publication is strict and atomic.
    const draftId=randomUUID(),rawDoc=store.normalizeDocument(document,a);
    const unfinished=structuredClone(rawDoc);unfinished.start_date='';unfinished.stops[0].expenses[0].amount='';
    const draftInput={document:unfinished,draft_revision:0,base_revision:0};
    let staged=await call('PUT',`/api/journeys/drafts/${draftId}`,draftInput);assert.equal(staged.revision,1);
    assert.equal((await call('PUT',`/api/journeys/drafts/${draftId}`,draftInput)).revision,1);
    await call('GET',`/api/journeys/drafts/${draftId}`,undefined,b,404);
    await call('PUT',`/api/journeys/drafts/${draftId}`,draftInput,b,404);
    await call('POST',`/api/journeys/drafts/${draftId}/publish`,{draft_revision:1},a,400);
    staged=await call('PUT',`/api/journeys/drafts/${draftId}`,{...draftInput,document:rawDoc,draft_revision:1});assert.equal(staged.revision,2);
    await call('PUT',`/api/journeys/drafts/${draftId}`,{...draftInput,document:{...rawDoc,title:'stale'},draft_revision:1},a,409);
    const diaryCount=sql.prepare('SELECT COUNT(*) AS n FROM Journey').get().n;
    const published=await call('POST',`/api/journeys/drafts/${draftId}/publish`,{draft_revision:2});
    assert.equal((await call('POST',`/api/journeys/drafts/${draftId}/publish`,{draft_revision:2})).id,published.id);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM Journey').get().n,diaryCount+1);
    await call('PUT',`/api/journeys/drafts/${draftId}`,{...draftInput,document:rawDoc,draft_revision:2},a,410);
    const staleDraftId=randomUUID();
    await call('PUT',`/api/journeys/drafts/${staleDraftId}`,{document:rawDoc,journey_id:journey.id,base_revision:4,draft_revision:0});
    store.saveJourney(a,{...rawDoc,title:'另一个窗口'},journey.id,4);
    await call('POST',`/api/journeys/drafts/${staleDraftId}/publish`,{draft_revision:1},a,409);
    assert.equal((await call('GET',`/api/journeys/drafts/${staleDraftId}`)).revision,1);
    const copied=await call('POST',`/api/journeys/drafts/${staleDraftId}/publish`,{draft_revision:1,as_copy:true});assert.notEqual(copied.id,journey.id);
    assert.equal(store.getJourney(a,journey.id).document.title,'另一个窗口');
    sql.prepare('UPDATE User SET is_banned=1 WHERE id=?').run(a);
    await call('POST','/api/journeys',{document},a,403);
    sql.prepare('DELETE FROM User WHERE id=?').run(a);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM Journey WHERE user_id=?').get(a).n,0);
    assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyJob WHERE user_id=?').get(a).n,0);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyJobRequest WHERE user_id=?').get(a).n,0);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyCorrection').get().n,0);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM JourneyDraft WHERE user_id=?').get(a).n,0);
    console.log('Journey integration tests passed: ownership, revisions, merging, media, share filtering, consent, discovery, logged draws, durable AI jobs and sequence ranking.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{
    global.fetch=nativeFetch;if(stopWorker)stopWorker();if(server)await new Promise(r=>server.close(r));sql.close();
    const resolved=path.resolve(temp);if(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('yuyuko-journeys-'))fs.rmSync(resolved,{recursive:true,force:true});
});
